apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: chatapp_be:${BUILD_NUMBER}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5001
          envFrom:
            - secretRef:
                name: fullstack-chatapp-k8s-secrets
          securityContext:
             runAsNonRoot: true
             runAsUser: 1000
             runAsGroup: 1000
             allowPrivilegeEscalation: false
             capabilities:
               drop: ["ALL"]
