apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-default-resources
spec:
  rules:
    - name: add-default-requests-limits
      match:
        resources:
          kinds:
            - Pod
      mutate:
        foreach:
          - list: "spec.containers"
            patchStrategicMerge:
              spec:
                containers:
                  - (name): "{{ element.name }}"
                    resources:
                      requests:
                        memory: "256Mi"
                        cpu: "500m"
                      limits:
                        memory: "512Mi"
                        cpu: "1"
