# 4-pv-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: db-gp3 
  resources:
    requests:
      storage: 25Gi
